apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
spec:
  selector:
      matchLabels:
        app: back-end
  replicas: 2
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - name: back-end
          image: abhinavtiwary/back-end
          imagePullPolicy: Always
          ports:
            - containerPort: 8090