apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front-end
spec:
  hosts:
  - "*"
  gateways:
  - poc-gateway
  http:
  - match:
    - uri:
        exact: /api/frontend
    route:
    - destination:
        host: front-end
        port:
          number: 80